export const ORDER_ITEMS = [
{"Id":1,"Itemname":"Samsung Galaxy S7 active","Customer":"Marj Ganter","Email":"mganter0@webs.com","Place":"Pune","OrderDate":"23-01-2024"},
{"Id":2,"Itemname":"Emporia Connect","Customer":"Evelin Cullnean","Email":"ecullnean1@engadget.com","Place":"Bengaluru","OrderDate":"22-04-2023"},
{"Id":3,"Itemname":"Karbonn S9 Titanium","Customer":"Maryrose Rosin","Email":"mrosin2@smh.com.au","Place":"Mumbai","OrderDate":"17-12-2023"},
{"Id":4,"Itemname":"Honor MagicWatch 2","Customer":"Karlens Iron","Email":"kiron3@buzzfeed.com","Place":"Kerala","OrderDate":"21-08-2023"},
{"Id":5,"Itemname":"Motorola C200","Customer":"Clovis Sarjent","Email":"csarjent4@columbia.edu","Place":"Nagpur","OrderDate":"26-03-2024"},
{"Id":6,"Itemname":"Amazon Fire HD 10 (2019)","Customer":"Alene MacLaren","Email":"amaclaren5@geocities.com","Place":"Delhi","OrderDate":"23-11-2023"},
{"Id":7,"Itemname":"Motorola DROID X ME811","Customer":"Allissa Borkett","Email":"aborkett6@godaddy.com","Place":"Delhi","OrderDate":"07-04-2024"},
{"Id":8,"Itemname":"Apple iPhone XS Max","Customer":"Woodman Jancso","Email":"wjancso7@ustream.tv","Place":"UP","OrderDate":"13-09-2023"},
{"Id":9,"Itemname":"Samsung Galaxy Note10+","Customer":"Mead Alexsandrev","Email":"malexsandrev8@theglobeandmail.com","Place":"Kolkatta","OrderDate":"26-06-2023"},
{"Id":10,"Itemname":"alcatel OT-300","Customer":"Trenton Jouannot","Email":"tjouannot9@amazon.co.jp","Place":"Bihar","OrderDate":"26-05-2023"},
{"Id":11,"Itemname":"Micromax Vdeo 2","Customer":"Carlen Oager","Email":"coagera@altervista.org","Place":"Bengaluru","OrderDate":"08-11-2023"},
{"Id":12,"Itemname":"Nokia 5","Customer":"Kennan Smouten","Email":"ksmoutenb@geocities.jp","Place":"Davanagere","OrderDate":"26-05-2023"},
{"Id":13,"Itemname":"Samsung Galaxy Victory 4G LTE L300","Customer":"Wallis Gillow","Email":"wgillowc@privacy.gov.au","Place":"Kochi","OrderDate":"10-02-2024"},
{"Id":14,"Itemname":"Siemens Xelibri 5","Customer":"Jamil Siely","Email":"jsielyd@imgur.com","Place":"Telangana","OrderDate":"03-08-2023"},
{"Id":15,"Itemname":"BLU Studio C Super Camera","Customer":"Daveen Snepp","Email":"dsneppe@kickstarter.com","Place":"AP","OrderDate":"07-03-2024"},
{"Id":16,"Itemname":"Philips W8510","Customer":"Karina Benka","Email":"kbenkaf@1und1.de","Place":"Madras","OrderDate":"11-04-2024"},
{"Id":17,"Itemname":"Amazon Kindle Fire HDX 8.9","Customer":"Earlie Crummay","Email":"ecrummayg@yellowbook.com","Place":"Tirupati","OrderDate":"28-06-2023"},
{"Id":18,"Itemname":"LG GM360 Viewty Snap","Customer":"Rafael Emmines","Email":"remminesh@disqus.com","Place":"Colombo","OrderDate":"13-06-2023"},
{"Id":19,"Itemname":"QMobile Noir i9","Customer":"Ailyn Jorgesen","Email":"ajorgeseni@nydailynews.com","Place":"Australia","OrderDate":"02-10-2023"},
{"Id":20,"Itemname":"ZTE nubia Z11 mini S","Customer":"Thurstan Martinovic","Email":"tmartinovicj@wordpress.org","Place":"Tokyo","OrderDate":"24-08-2023"},
{"Id":21,"Itemname":"Acer beTouch E120","Customer":"Idell Sabater","Email":"isabaterk@java.com","Place":"US","OrderDate":"28-03-2024"},
{"Id":22,"Itemname":"HTC U11+","Customer":"Susette Rottenbury","Email":"srottenburyl@gmpg.org","Place":"Germany","OrderDate":"06-03-2024"},
{"Id":23,"Itemname":"Samsung E690","Customer":"Nola Membry","Email":"nmembrym@stanford.edu","Place":"Erie","OrderDate":"11-01-2024"},
{"Id":24,"Itemname":"Samsung M2510","Customer":"Caterina Munson","Email":"cmunsonn@go.com","Place":"California","OrderDate":"17-03-2024"},
{"Id":25,"Itemname":"Sagem MY X-6","Customer":"Mandi Hallihan","Email":"mhallihano@washington.edu","Place":"Paris","OrderDate":"21-04-2023"},
{"Id":26,"Itemname":"Huawei IDEOS S7 Slim CDMA","Customer":"Hedwiga Head","Email":"hheadp@mapquest.com","Place":"Maldives","OrderDate":"29-11-2023"},
{"Id":27,"Itemname":"alcatel 10.16G","Customer":"Carlos Ghidini","Email":"cghidiniq@vk.com","Place":"Mangalore","OrderDate":"22-05-2023"},
{"Id":28,"Itemname":"Honor 7","Customer":"Natty Degoix","Email":"ndegoixr@tripadvisor.com","Place":"Shimoga","OrderDate":"05-01-2024"},
{"Id":29,"Itemname":"Philips V726","Customer":"Happy Prydden","Email":"hpryddens@imageshack.us","Place":"Channagiri","OrderDate":"10-06-2023"},
{"Id":30,"Itemname":"Samsung i710","Customer":"Fielding Griffitts","Email":"fgriffittst@123-reg.co.uk","Place":"Kolar","OrderDate":"24-11-2023"},
{"Id":31,"Itemname":"Panasonic X800","Customer":"Doria Guiver","Email":"dguiveru@wikispaces.com","Place":"Shikharipura","OrderDate":"30-05-2023"},
{"Id":32,"Itemname":"Plum Optimax 10","Customer":"Karlens Scarlin","Email":"kscarlinv@t.co","Place":"Chitradurga","OrderDate":"01-06-2023"},
{"Id":33,"Itemname":"Sharp 705SH","Customer":"Myer Ridge","Email":"mridgew@addthis.com","Place":"Coimbra","Delhi":"09-11-2023"},
{"Id":34,"Itemname":"Acer Liquid S1","Customer":"Filia Kegley","Email":"fkegleyx@163.com","Place":"UP","OrderDate":"23-05-2023"},
{"Id":35,"Itemname":"Plum Optimax 2","Customer":"Inesita Chadney","Email":"ichadneyy@dropbox.com","Place":"Kashmir","OrderDate":"12-08-2023"},
{"Id":36,"Itemname":"Samsung T819","Customer":"Huntlee Cristofolo","Email":"hcristofoloz@sphinn.com","Place":"Kerala","OrderDate":"01-06-2023"},
{"Id":37,"Itemname":"Plum Sync 3.5","Customer":"Ardith Jakoviljevic","Email":"ajakoviljevic10@shinystat.com","Place":"Vizag","OrderDate":"07-02-2024"},
{"Id":38,"Itemname":"Spice S-1200","Customer":"Kelsi Scrimshire","Email":"kscrimshire11@goodreads.com","Place":"Kurnool","OrderDate":"18-03-2024"},
{"Id":39,"Itemname":"Huawei G7010","Customer":"Candice Obee","Email":"cobee12@ibm.com","Place":"Coimbra","OrderDate":"16-05-2023"},
{"Id":40,"Itemname":"Celkon C201","Customer":"Clarissa Costley","Email":"ccostley13@delicious.com","Place":"Coimbra","OrderDate":"03-01-2024"},
{"Id":41,"Itemname":"LG Viper 4G LTE LS840","Customer":"Melodee Vila","Email":"mvila14@studiopress.com","Place":"Coimbra","OrderDate":"29-12-2023"},
{"Id":42,"Itemname":"Samsung Galaxy Watch","Customer":"Thomas Goodall","Email":"tgoodall15@blogger.com","Place":"Coimbra","OrderDate":"30-08-2023"},
{"Id":43,"Itemname":"Philips Genie Sport","Customer":"Feliza Fick","Email":"ffick16@cmu.edu","Place":"Coimbra","OrderDate":"12-01-2024"},
{"Id":44,"Itemname":"i-mobile 320","Customer":"Shoshanna Vakhrushin","Email":"svakhrushin17@china.com.cn","Place":"Coimbra","OrderDate":"29-06-2023"},
{"Id":45,"Itemname":"Allview Allwatch V","Customer":"Sarene Annes","Email":"sannes18@desdev.cn","Place":"Coimbra","OrderDate":"16-10-2023"},
{"Id":46,"Itemname":"Nokia 3120 classic","Customer":"Cortney Casarini","Email":"ccasarini19@comcast.net","Place":"Coimbra","OrderDate":"20-10-2023"},
{"Id":47,"Itemname":"Motorola C113","Customer":"Jasen Botwood","Email":"jbotwood1a@forbes.com","Place":"Coimbra","OrderDate":"15-10-2023"},
{"Id":48,"Itemname":"Nokia 2650","Customer":"Hermine MacCumiskey","Email":"hmaccumiskey1b@163.com","Place":"Coimbra","OrderDate":"04-06-2023"},
{"Id":49,"Itemname":"BlackBerry Priv","Customer":"Fabe Verlander","Email":"fverlander1c@mit.edu","Place":"Coimbra","OrderDate":"30-03-2024"},
{"Id":50,"Itemname":"Motorola Moto E5","Customer":"Abby Cunrado","Email":"acunrado1d@epa.gov","Place":"Coimbra","OrderDate":"20-08-2023"},
{"Id":51,"Itemname":"LG A100","Customer":"Jewelle Houlston","Email":"jhoulston1e@networkadvertising.org","Place":"Coimbra","OrderDate":"11-07-2023"},
{"Id":52,"Itemname":"BLU Studio Energy 2","Customer":"Pepe Ledgerton","Email":"pledgerton1f@bbc.co.uk","Place":"Coimbra","OrderDate":"15-10-2023"},
{"Id":53,"Itemname":"Spice QT-52","Customer":"Lusa Longworth","Email":"llongworth1g@mapy.cz","Place":"Coimbra","OrderDate":"18-06-2023"},
{"Id":54,"Itemname":"Acer Iconia Tab A3-A20","Customer":"Minnaminnie Sloey","Email":"msloey1h@soup.io","Place":"Coimbra","OrderDate":"09-04-2024"},
{"Id":55,"Itemname":"Plum Might","Customer":"Cecil Haddow","Email":"chaddow1i@blinklist.com","Place":"Coimbra","OrderDate":"30-07-2023"},
{"Id":56,"Itemname":"Xiaomi Redmi 3s","Customer":"Joannes Luton","Email":"jluton1j@discuz.net","Place":"Coimbra","OrderDate":"04-09-2023"},
{"Id":57,"Itemname":"Lenovo Z5","Customer":"Arnie Walworche","Email":"awalworche1k@census.gov","Place":"Coimbra","OrderDate":"16-11-2023"},
{"Id":58,"Itemname":"Huawei G5500","Customer":"Isadora Lerohan","Email":"ilerohan1l@liveinternet.ru","Place":"Coimbra","OrderDate":"02-07-2023"},
{"Id":59,"Itemname":"Plum Might Pro","Customer":"Padgett Chapling","Email":"pchapling1m@hugedomains.com","Place":"Coimbra","OrderDate":"09-07-2023"},
{"Id":60,"Itemname":"OnePlus Nord N100","Customer":"Shaina Peirone","Email":"speirone1n@skype.com","Place":"Coimbra","OrderDate":"24-11-2023"},
{"Id":61,"Itemname":"Plum Trion","Customer":"Theodor Logie","Email":"tlogie1o@elpais.com","Place":"Coimbra","OrderDate":"30-12-2023"},
{"Id":62,"Itemname":"Samsung Galaxy S II LTE I9210","Customer":"Gifford Foden","Email":"gfoden1p@baidu.com","Place":"Coimbra","OrderDate":"01-04-2024"},
{"Id":63,"Itemname":"Sony Xperia XA1 Plus","Customer":"Ase Yoakley","Email":"ayoakley1q@is.gd","Place":"Coimbra","OrderDate":"27-11-2023"},
{"Id":64,"Itemname":"Lenovo K6 Power","Customer":"Rhona Kayser","Email":"rkayser1r@toplist.cz","Place":"Coimbra","OrderDate":"22-05-2023"},
{"Id":65,"Itemname":"Celkon A 107+","Customer":"Matelda Henriquet","Email":"mhenriquet1s@photobucket.com","Place":"Coimbra","OrderDate":"06-09-2023"},
{"Id":66,"Itemname":"Allview Viva D8","Customer":"Gabie Gritten","Email":"ggritten1t@smh.com.au","Place":"Coimbra","OrderDate":"21-08-2023"},
{"Id":67,"Itemname":"Wiko Rainbow Jam","Customer":"Marten Bakhrushin","Email":"mbakhrushin1u@usa.gov","Place":"Coimbra","OrderDate":"31-07-2023"},
{"Id":68,"Itemname":"Sony Xperia 1 II","Customer":"Nerti Fawdry","Email":"nfawdry1v@imageshack.us","Place":"Coimbra","OrderDate":"25-10-2023"},
{"Id":69,"Itemname":"BenQ-Siemens EF61","Customer":"Ardelia Di Napoli","Email":"adi1w@abc.net.au","Place":"Coimbra","OrderDate":"07-03-2024"},
{"Id":70,"Itemname":"Huawei Fusion 2 U8665","Customer":"Graham Grinikhinov","Email":"ggrinikhinov1x@reddit.com","Place":"Coimbra","OrderDate":"10-06-2023"},
{"Id":71,"Itemname":"Ulefone Armor X2","Customer":"Ardeen Busen","Email":"abusen1y@mashable.com","Place":"Coimbra","OrderDate":"21-11-2023"},
{"Id":72,"Itemname":"Nokia 207","Customer":"Efrem Starmore","Email":"estarmore1z@lulu.com","Place":"Coimbra","OrderDate":"07-05-2023"},
{"Id":73,"Itemname":"Samsung Galaxy Watch3","Customer":"Dionne Andryunin","Email":"dandryunin20@prlog.org","Place":"Coimbra","OrderDate":"19-09-2023"},
{"Id":74,"Itemname":"O2 X2","Customer":"Amie Burde","Email":"aburde21@tamu.edu","Place":"Coimbra","OrderDate":"27-06-2023"},
{"Id":75,"Itemname":"Micromax A45","Customer":"Blithe Hamill","Email":"bhamill22@odnoklassniki.ru","Place":"Coimbra","OrderDate":"29-12-2023"},
{"Id":76,"Itemname":"Telit GM 882","Customer":"Dolorita Chmiel","Email":"dchmiel23@acquirethisname.com","Place":"Coimbra","OrderDate":"01-06-2023"},
{"Id":77,"Itemname":"HTC One M9+ Supreme Camera","Customer":"Bertine Orme","Email":"borme24@patch.com","Place":"Coimbra","OrderDate":"23-05-2023"},
{"Id":78,"Itemname":"Nokia 6500 slide","Customer":"Sophia Redgate","Email":"sredgate25@dyndns.org","Place":"Coimbra","OrderDate":"06-01-2024"},
{"Id":79,"Itemname":"ZTE Grand S II S291","Customer":"Regen Grimshaw","Email":"rgrimshaw26@auda.org.au","Place":"Coimbra","OrderDate":"25-04-2023"},
{"Id":80,"Itemname":"Samsung Exhibit 4G","Customer":"Sayre Norgan","Email":"snorgan27@furl.net","Place":"Coimbra","OrderDate":"22-04-2023"},
{"Id":81,"Itemname":"Celkon A69","Customer":"Daloris Falloon","Email":"dfalloon28@twitter.com","Place":"Coimbra","OrderDate":"27-09-2023"},
{"Id":82,"Itemname":"Tecno Pouvoir 1","Customer":"Roana Chidley","Email":"rchidley29@infoseek.co.jp","Place":"Coimbra","OrderDate":"22-09-2023"},
{"Id":83,"Itemname":"vivo Y11 (2019)","Customer":"Boot Twitchett","Email":"btwitchett2a@chron.com","Place":"Coimbra","OrderDate":"16-11-2023"},
{"Id":84,"Itemname":"Sewon SG-2100CS","Customer":"Nanete Grogono","Email":"ngrogono2b@blogger.com","Place":"Coimbra","OrderDate":"03-09-2023"},
{"Id":85,"Itemname":"BLU Touch Book 7.0","Customer":"Lizbeth Culkin","Email":"lculkin2c@businesswire.com","Place":"Coimbra","OrderDate":"25-03-2024"},
{"Id":86,"Itemname":"Motorola V975","Customer":"Sascha Eltun","Email":"seltun2d@google.co.uk","Place":"Coimbra","OrderDate":"09-02-2024"},
{"Id":87,"Itemname":"Celkon A119 Signature HD","Customer":"Blinny Fauning","Email":"bfauning2e@goodreads.com","Place":"Coimbra","OrderDate":"20-06-2023"},
{"Id":88,"Itemname":"Plum Stubby II","Customer":"Bobina Burroughes","Email":"bburroughes2f@shareasale.com","Place":"Coimbra","OrderDate":"07-07-2023"},
{"Id":89,"Itemname":"Acer Iconia One 7 B1-730","Customer":"Cleve Van Arsdalen","Email":"cvan2g@xing.com","Place":"Coimbra","OrderDate":"25-07-2023"},
{"Id":90,"Itemname":"alcatel Watch","Customer":"Wendye Shillaker","Email":"wshillaker2h@about.me","Place":"Coimbra","OrderDate":"25-10-2023"},
{"Id":91,"Itemname":"Sony Xperia S","Customer":"Isa Baines","Email":"ibaines2i@nbcnews.com","Place":"Coimbra","OrderDate":"06-02-2024"},
{"Id":92,"Itemname":"Tecno Spark Go","Customer":"Craig Cuttle","Email":"ccuttle2j@marketwatch.com","Place":"Coimbra","OrderDate":"04-07-2023"},
{"Id":93,"Itemname":"Celkon C202","Customer":"Hedvige Sansome","Email":"hsansome2k@jimdo.com","Place":"Coimbra","OrderDate":"10-01-2024"},
{"Id":94,"Itemname":"Lava A73","Customer":"Lonee Lettson","Email":"llettson2l@furl.net","Place":"Coimbra","OrderDate":"16-12-2023"},
{"Id":95,"Itemname":"BLU Vivo 8","Customer":"Aurea Dilworth","Email":"adilworth2m@google.cn","Place":"Coimbra","OrderDate":"03-07-2023"},
{"Id":96,"Itemname":"Samsung i505","Customer":"Lark Castle","Email":"lcastle2n@bigcartel.com","Place":"Coimbra","OrderDate":"03-01-2024"},
{"Id":97,"Itemname":"i-mobile 5220","Customer":"Davita Ginnelly","Email":"dginnelly2o@photobucket.com","Place":"Coimbra","OrderDate":"11-05-2023"},
{"Id":98,"Itemname":"Icemobile Hurricane II","Customer":"Sibylle Reston","Email":"sreston2p@google.it","Place":"Coimbra","OrderDate":"14-10-2023"},
{"Id":99,"Itemname":"Sharp GX33","Customer":"Omero Ibbeson","Email":"oibbeson2q@sitemeter.com","Place":"Coimbra","OrderDate":"18-03-2024"},
{"Id":100,"Itemname":"Sendo SV663","Customer":"Craggy Robion","Email":"crobion2r@alexa.com","Place":"Coimbra","OrderDate":"13-04-2024"}]